language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
  - openjdk8
notifications:
  email:
    recipients:
      - drazzib@drazzib.com
    on_success: change
    on_failure: always
